// export default class Color{
//     static vermelho: any = "#AD1313"
//     static vermelhoEscuro: any = "#660B0B"
//     static branco: any = "#fff"
//     static placeholder: any = "#CCCCCC"
//     static cinzaEscuro: any = "#808080"
//     static cinzaClaro: any = "#D9D9D9"
//     static cinzaTransparente: any = "rgba(217, 217, 217, 0.9)"
//     static vermelhoAcinzentado: any = "#d5c5c5"
//     static vermelhoAviso: any = "#f00"
//     static keyboardBackground: any = "#ECEFF1"
//     static keyBackground: any = "#FBFCFC"
//     static keyColor: any = "#2E414A"
// }

export default class Color{
    static vermelho: any = "#AD1313"
    static vermelhoEscuro: any = "#660B0B"
    static branco1: any = "#000"
    static branco2: any = "#363636"
    //static branco: any = "#fff"
    //static placeholder: any = "#CCCCCC"
    static placeholder: any = "#363636"
    //static cinzaEscuro: any = "#808080"
    static cinzaEscuro: any = "#CCCCCC"
    //static cinzaClaro: any = "#D9D9D9"
    static cinzaClaro: any = "#6d6d6d"
    //static cinzaTransparente: any = "rgba(217, 217, 217, 0.9)"
    static cinzaTransparente: any = "rgba(54, 54, 54, 0.7)"
    //static vermelhoAcinzentado: any = "#d5c5c5"
    static vermelhoAcinzentado: any = "rgb(68,41,41)"
    static vermelhoAviso: any = "#f00"
    static keyboardBackground: any = "#ECEFF1"
    static keyBackground: any = "#FBFCFC"
    static keyColor: any = "#2E414A"
}